@startuml Chinese_Flashcard_UseCase 
left to right direction 
skinparam packageStyle rectangle

actor user 
actor admin 

rectangle Chinese_Flashcard {
	user -- (Register)
	(Login) .> (Register) : include 
	(Register) -- admin 
	user -- (Login)
	(Login) -- admin 
	user -- (Search Word)
	user -- (Interact with Word to learn)
	user -- (Favorite Word)
	user -- (Create Personal Category)
	user -- (Update Personal Category)
	user -- (Delete Personal Category)
	user -- (Add Words to Personal Category)
	user -- (Quiz) 
	user -- (Update User Profile)
	(Create Word) -- admin 
	(Update Word) -- admin 
	(Delete Word) -- admin 
}

@enduml